### PR TITLE
Allow direct links to messages in IRC logs.

### PR DESCRIPTION
**Pull request by ddmgy**
In reference to #4.

Click timestamp on left edge of IRC logs to get a direct link to that message.

### CODE REVIEW

**Comment by dom96** [comment]
Sorry I didn't get around to reviewing this yet. May need another couple of days.

**Comment by dom96** [comment]
Haven't forgotten about this, sorry for the wait.

**Comment by ddmgy** [comment]
It's no problem; I had almost forgotten about it, anyway.

If there's anything that you feel needs to be changed, let me know.

**Comment by dom96** [comment]
Why did you close this?!

**Comment by ddmgy** [comment]
Whoops. I was clearing out a bunch of (mostly private) repos I didn't need
anymore last night, and I didn't recognize the name. I'll see if I can
restore from my local copy later.

**Pull request closed without merging**
